version: '3.7'
services:
  keycloak_db:
    image: postgres:10
    restart: always
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak_db
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    restart: always
    ports:
      - '8443:8443'
      - '8082:8080'
    command: start-dev --import-realm
    volumes:
      - ./src/backend/keycloak/imports:/opt/keycloak/data/import
      - ./src/backend/keycloak/keystore:/opt/conf
    # TODO: Fix this warning, (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db/keycloak_db?user=keycloak&password=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      #      - KC_HTTPS_KEY_STORE_FILE=/opt/conf/server.keystore
      #      - KC_HTTPS_KEY_STORE_PASSWORD=password
      - KC_TRANSACTION_XA_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    depends_on:
      - keycloak_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/realms/phyloviz-web-platform"]

  gateway:
    build:
      context: ./src/backend/microservices/gateway
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    network_mode: host
    environment:
      MANAGEMENT_METRICS_BINDERS_PROCESSOR_ENABLED: "false"
      MANAGEMENT_METRICS_BINDERS_SYSTEM_ENABLED: "false"
      MANAGEMENT_METRICS_ENABLE_SYSTEM: "false"
      MANAGEMENT_METRICS_ENABLE_PROCESS: "false"
      JAVA_TOOL_OPTIONS: "-XX:-UseContainerSupport"
    depends_on:
      - keycloak


volumes:
  keycloak_db_data:
    driver: local
  cache:
    driver: local
  mongodb-data:
    driver: local
  tool-registry-data:
    driver: local
