s3:
  access-key-id: AKIAS6J7QENFXF6QXBIY
  secret-access-key: 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
  bucket: phyloviz
  region: eu-north-1
  endpoint: https://s3.eu-north-1.amazonaws.com

spring:
  data:
    mongodb:
      host: localhost
      port: 28017
      database: phyloviz-web-platform
      authentication-database: admin
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8082/realms/phyloviz-web-platform/protocol/openid-connect/token/introspect
          client-id: phyloviz-web-platform-client
          client-secret: YgBdr86Ngwibo98YoVGFHzD9n9sOlvgh
#        jwt:
#          jwk-set-uri: http://localhost:8082/realms/phyloviz-web-platform/protocol/openid-connect/certs